 - name: SOCaaC PLAYBOOK 2 --- Install TheHive Locally [Stock]
  hosts: localhost
  gather_facts: false
  become: yes
  tasks:
    - name: Download custom installation script
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/videxrealone/testSOC/main/install.sh"
        dest: "/tmp/install.sh"
        mode: "u=rwx,g=rx,o=rx"
        validate_certs: yes

    - name: Ensure script is executable
      ansible.builtin.file:
        path: "/tmp/install.sh"
        mode: "u=rwx,g=rx,o=rx"

    - name: Run installation script with input
      ansible.builtin.shell:
        cmd: |
          echo 2 | bash /tmp/install.sh
      args:
        executable: /bin/bash

    - name: Print message
      ansible.builtin.debug:
        msg: "Installation successful - TheHive is now running on http://localhost:9000 . Please login with admin@thehive.local:secret"